### PR TITLE
Support Tsdl 1.0.0

### PR DESCRIPTION
**Pull request by jonahbeckford**
Add events for Tsdl 1.0.0.

Tests:
- Tested compilation with Tsdl 0.9.8
- Tested runs with Tsdl 1.0.0

### CODE REVIEW

**Comment by sanette** [comment]
thanks! however this overlaps https://github.com/sanette/bogue/pull/18
(moved to the`power_saving` branch)
And in fact, it's probably better (and a relief) that we can now use
`type sdl_event = Sdl.Event.enum`

**Comment by jonahbeckford** [comment]
Edwin's PRs would be much better, and `Sdl.Event.enum` seems clean.

Let's close this if you have decided to merge that PR.

**Comment by sanette** [comment]
could you try if the `power_saving` branch works for you?

**Comment by jonahbeckford** [comment]
I switched to `power_saving` branch and then:
1. Cherry-picked commit https://github.com/sanette/bogue/commit/ad184ee5fad2821eb794633a4f21fb75bd5a3928 (`Switch [directories] to [xdg] to work on Windows`).
2. Changed to `type sdl_event = Tsdl.Sdl.Event.enum`

Yes, that worked although same errors (as expected) as #32 .

**Comment by sanette** [comment]
> 2\. Changed to `type sdl_event = Tsdl.Sdl.Event.enum`

oh yes, sorry, I forgot that in fact I split the PR and this change was pushed to the `vsync` branch

**Comment by jonahbeckford** [comment]
No need for this so closing. ~Although the master branch does not compile if the `type sdl_event = Tsdl.Sdl.Event.enum` changes are not present.~

**Pull request closed without merging**
